### ISSUE TITLE
Execution of scripts freezes when opening node editor

### ISSUE THREAD

**Issue by HaaiHenkie** [HaaiHenkie/FreeIBIS#2]
When starting `fiIdea.groovy` with an issue or position node selected, the script will create the new node with the `idea` icon, but will hang on the splash screen of the Simpy HTML editor.

![image](https://user-images.githubusercontent.com/8525411/101268331-07ac7f00-3762-11eb-9436-87a6af97f60a.png)

The Freeplane log file shows the following warning:

```
STDOUT: dec. 06, 2020 1:25:28 A.M. org.freeplane.core.util.LogUtils warn
WARNING: Loading of WYSIWYG HTML editor failed. Use the other editors instead.
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "preferences")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:216)
	at java.prefs/java.util.prefs.Preferences.userRoot(Preferences.java:455)
	at java.prefs/java.util.prefs.Preferences.userNodeForPackage(Preferences.java:371)
	at com.lightdev.app.shtm.SHTMLEditorPane$PasteMode.getValueFromPrefs(SHTMLEditorPane.java:163)
	at com.lightdev.app.shtm.SHTMLEditorKitActions$SHTMLEditPasteOtherAction.<init>(SHTMLEditorKitActions.java:2150)
	at com.lightdev.app.shtm.SHTMLPanelImpl.initActions(SHTMLPanelImpl.java:722)
	at com.lightdev.app.shtm.SHTMLPanelSingleDocImpl.initActions(SHTMLPanelSingleDocImpl.java:41)
	at com.lightdev.app.shtm.SHTMLPanelImpl.<init>(SHTMLPanelImpl.java:245)
	at com.lightdev.app.shtm.SHTMLPanelSingleDocImpl.<init>(SHTMLPanelSingleDocImpl.java:24)
	at com.lightdev.app.shtm.SHTMLPanel.createSHTMLPanel(SHTMLPanel.java:63)
	at org.freeplane.features.text.mindmapmode.MTextController.createSHTMLPanel(MTextController.java:1055)
	at org.freeplane.features.text.mindmapmode.EditNodeWYSIWYG$HTMLDialog.createEditorPanel(EditNodeWYSIWYG.java:120)
	at org.freeplane.features.text.mindmapmode.EditNodeWYSIWYG$HTMLDialog.<init>(EditNodeWYSIWYG.java:67)
	at org.freeplane.features.text.mindmapmode.EditNodeWYSIWYG.createHtmlEditor(EditNodeWYSIWYG.java:308)
	at org.freeplane.features.text.mindmapmode.EditNodeWYSIWYG.show(EditNodeWYSIWYG.java:238)
	at org.freeplane.features.text.mindmapmode.MTextController.edit(MTextController.java:983)
	at org.freeplane.features.text.mindmapmode.MTextController.edit(MTextController.java:795)
	at org.freeplane.plugin.script.proxy.ControllerProxy.editImpl(ControllerProxy.java:75)
	at org.freeplane.plugin.script.proxy.ControllerProxy.editInPopup(ControllerProxy.java:69)
	at org.freeplane.api.Controller$editInPopup.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at fiIdea.run(fiIdea.groovy:14)
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:116)
	at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
	at org.freeplane.plugin.script.ExecuteScriptAction.actionPerformed(ExecuteScriptAction.java:93)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at org.freeplane.core.ui.ActionAcceleratorManager.processKeyBinding(ActionAcceleratorManager.java:436)
	at org.freeplane.main.mindmapmode.MModeControllerFactory$2.processKeyBinding(MModeControllerFactory.java:288)
	at org.freeplane.view.swing.ui.UserInputListenerFactory$2.processKeyBinding(UserInputListenerFactory.java:172)
	at org.freeplane.core.ui.components.FreeplaneMenuBar.processKeyBinding(FreeplaneMenuBar.java:99)
	at org.freeplane.main.application.MenuKeyProcessor.processKeyBinding(MenuKeyProcessor.java:26)
	at org.freeplane.main.application.ConnectedToMenuView.processKeyBinding(ConnectedToMenuView.java:41)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The solution is to set property `execute_scripts_without_write_restriction` to `true` for all FreeIBIS scripts in the add-on definition mind map.

**Comment by HaaiHenkie** [comment]
Fixed in commit 805ff04
